[project]
name = "agno-curso"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "juvenalculino", email = "b831381@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "agno>=3.0.10",
    "chromadb>=1.5.9",
    "fastapi>=0.141.1",
    "google-genai>=2.24.0",
    "groq>=1.7.0",
    "openai>=3.15.0",
    "pgvector>=0.5.0",
    "pypdf>=6.19.0",
    "python-dotenv>=1.2.3",
    "python-multipart>=0.0.32",
    "sentence-transformers>=6.1.0",
    "sqlalchemy>=2.0.54",
    "streamlit>=1.64.0",
    "tavily-python>=0.8.3",
    "uvicorn>=0.53.0",
    "yfinance>=1.7.0",
]

[project.scripts]
agno-curso = "agno_curso:main"

[build-system]
requires = ["uv_build>=0.12.16,<0.13.0"]
build-backend = "uv_build"
